services:
  postgres:
    image: postgres:16-alpine
    container_name: habit_tracker_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: habit_pass_2026
      POSTGRES_DB: habit_tracker
    volumes:
      - habit_data:/var/lib/postgresql/data

volumes:
  habit_data:
